apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      version: 6.3.6
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    replicaCount: 1
    ui:
      message: ""
      logo: ""
    image:
      repository: ghcr.io/stefanprodan/podinfo
      tag: 6.3.6
    serviceAccount:
      name: default
    ingress:
      enabled: true
      hosts:
      - host: podinfo.ocm.dev
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
       - secretName: mkcert-tls
         hosts:
           - podinfo.ocm.dev
