apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: capacitor
  namespace: ocm-system
spec:
  interval: 1m0s
  component: ocm.software/demos/capacitor
  repository:
    url: gitea.ocm.dev/software-provider
    secretRef:
      name: gitea-registry-credentials
  destination:
    url: gitea.ocm.dev/software-consumer
    secretRef:
      name: gitea-registry-credentials
  version:
    semver: ">=v1.0.0"
  verify:
  - name: ocm-signing
    publicKey:
      secretRef:
        name: ocm-signing
