apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: capacitor
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    kind: Configuration
    name: capacitor
  kustomizationTemplate:
    interval: 1m0s
    path: ./
    prune: true
    targetNamespace: default
