apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: weave-gitops
  namespace: ocm-system
spec:
  interval: 1m0s
  component: ocm.software/demos/weave-gitops
  repository:
    url: gitea.ocm.dev/private-org
  version:
    semver: ">=v1.0.0"
  verify:
  - name: ocm-signing
    publicKey:
      secretRef:
        name: ocm-signing
