# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# see: https://github.com/open-component-model/.github/blob/main/.github/settings.yml
_extends: .github

repository:
  topics: ocm, open-component-model, demo

labels:
- name: repo/demo-secure-delivery
  color: bfd4f2
