apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
  labels:
    env: test
configuration:
  defaults:
    message: "This is the backend service"
    replicas: 1
  rules:
  - value: (( message ))
    file: configmap.yaml
    path: data.PODINFO_UI_MESSAGE
  - value: (( replicas ))
    file: deploy.yaml
    path: spec.replicas
  schema:
    type: object
    additionalProperties: false
    properties:
      replicas:
        type: integer
      message:
        type: string
localization:
- resource:
    name: image
  file: deploy.yaml
  image: spec.template.spec.containers[0].image
