apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  component: ocm.software/demos/podinfo
  version:
    semver: ">=v1.0.0"
  repository:
    url: ghcr.io/phoban01
