apiVersion: delivery.ocm.software/v1alpha1
kind: Configuration
metadata:
  name: podinfo-deployment
  namespace: ocm-system
spec:
  interval: 5m
  sourceRef:
    kind: Localization
    name: podinfo-deployment
  configRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: config
      version: latest
  values:
    message: "Hello from ocm-controller"
    replicas: 2
