apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
localization:
- file: oci_repository.yaml
  mapping:
    path: spec.url
    transform: |-
          package main
          import (
            "encoding/json"
            "path"
          )
          result: string
          for x in component.resources {
            if x.name == "chart" {
              result: path.Dir(x.access.imageReference)
            }
          }
          out: json.Marshal("oci://"+result)
