apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  sourceRef:
    kind: Configuration
    name: podinfo-deployment
  kustomizationTemplate:
    interval: 2m0s
    path: ./
    prune: true
    targetNamespace: default
