apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.22"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
  values:
    image:
      repository: ghcr.io/weaveworks/wego-app
      tag: "v0.24.0"
    adminUser:
      create: true
      username: admin
      passwordHash: $2a$10$fd4RWR8q.oMNir6.AcXIcOSUFrFBsgUDCIyEB/j/9JFgDxzlc0oP.
    ingress:
      enabled: true
      hosts:
      - host: weave-gitops.ocm.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
       - secretName: mkcert-tls
         hosts:
           - weave-gitops.ocm.dev
