apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10s
  sourceRef:
    kind: Configuration
    name: podinfo
  kustomizationTemplate:
    interval: 30s
    path: ./
    prune: true
    targetNamespace: default
