apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 30s
  sourceRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: manifests
      version: latest
  configRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: config
      version: latest
