apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bootstrap-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bootstrap-certificate
  namespace: ocm-system
spec:
  # this is discouraged but required by ios
  commonName: cert-manager-ocm-tls
  isCA: true
  secretName: ocm-registry-tls-certs
  subject:
    organizations:
      - ocm.software
  dnsNames:
    - gitea.ocm.dev
    - capacitor.ocm.dev
    - podinfo.ocm.dev
    - ci.ocm.dev
    - events.ci.ocm.dev
    - registry.ocm-system.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certificate-issuer
spec:
  ca:
    secretName: ocm-registry-tls-certs
