apiVersion: config.ocm.software/v1alpha1
kind: ConfigData
metadata:
  name: ocm-config
  labels:
    env: test
configuration:
  defaults:
    color: "#34577c"
    message: "This is the backend service"
    replicas: 1
    serviceAccountName: "default"
  rules:
  - value: (( message ))
    file: configmap.yaml
    path: data.PODINFO_UI_MESSAGE
  - value: (( color ))
    file: configmap.yaml
    path: data.PODINFO_UI_COLOR
  - value: (( replicas ))
    file: backend.yaml
    path: spec.replicas
  - value: (( serviceAccountName ))
    file: backend.yaml
    path: spec.template.spec.serviceAccountName
  - value: (( base64(message) ))
    file: backend.yaml
    path: spec.template.metadata.annotations.roll
  - value: (( base64(join( " ", message,color)) ))
    file: backend.yaml
    path: spec.template.metadata.annotations.roll
  schema:
    type: object
    additionalProperties: false
    properties:
      replicas:
        type: string
      message:
        type: string
      serviceAccountName:
        type: string
      color:
        type: string
localization:
- resource:
    name: podinfo
  file: backend.yaml
  image: spec.template.spec.containers[0].image
