apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@gitea-ssh.gitea:2222/software-consumer/ocm-applications.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kind
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
