apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinfo-subscription
  namespace: ocm-system
spec:
  interval: 10m0s
  component: ocm.software/demos/podinfo
  semver: ">=v1.0.0"
  source:
    url: gitea.ocm.dev/public-org
    secretRef:
      name: gitea-registry-credentials
  destination:
    url: gitea.ocm.dev/private-org
    secretRef:
      name: gitea-registry-credentials
  verify:
  - name: ocm-signing
    publicKey:
      secretRef:
        name: ocm-signing
