---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-component
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./components/podinfo
  prune: true
  dependsOn:
  - name: weave-gitops-component
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops-component
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./components/weave-gitops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
