---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-component
  namespace: flux-system
spec:
  interval: 30s
  path: ./components/podinfo
  prune: true
  dependsOn:
  - name: capacitor-component
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor-component
  namespace: flux-system
spec:
  interval: 30s
  path: ./components/capacitor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
