---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-component
  namespace: flux-system
spec:
  interval: 30s
  path: ./components/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
